name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Actividad4 Accion1
        uses: docker/setup-qemu-action@v1
      -
        name: Actividad4 Accion2
        uses: docker/setup-buildx-action@v1
      -
        name: Actividad4 Accion3
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Actividad4 Accion4
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: borispalacios/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}